export const GET_EVENT_LIST_REQUEST_INITIATED = 'GET_EVENT_LIST_REQUEST_INITIATED';

export const GET_EVENT_LIST_REQUEST_ERROR = 'GET_EVENT_LIST_REQUEST_ERROR';

export const GET_EVENT_LIST_REQUEST_COMPLETED = 'GET_EVENT_LIST_REQUEST_COMPLETED';

export const ADD_EVENT_REQUEST_INITIATED = 'ADD_EVENT_REQUEST_INITIATED';

export const ADD_EVENT_REQUEST_ERROR = 'ADD_EVENT_REQUEST_ERROR';

export const ADD_EVENT_REQUEST_COMPLETED = 'ADD_EVENT_REQUEST_COMPLETED';

export const MODIFY_EVENT_REQUEST_INITIATED = 'MODIFY_EVENT_REQUEST_INITIATED';

export const MODIFY_EVENT_REQUEST_ERROR = 'MODIFY_EVENT_REQUEST_ERROR';

export const MODIFY_EVENT_REQUEST_COMPLETED = 'MODIFY_EVENT_REQUEST_COMPLETED';

export default GET_EVENT_LIST_REQUEST_INITIATED;